DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS books;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL
);

CREATE TABLE books (
    id SERIAL PRIMARY KEY,
    isbn VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    pages INT NOT NULL,
    created_at TIMESTAMP NOT NULL
);